### ISSUE TITLE
Create guide for local backend rollout

### ISSUE THREAD

**Issue by ro-jar** [TelemedDevGroup/TelemedProtoApp#23]

**Comment by ykorobitsin** [comment]
https://github.com/TelemedDevGroup/TelemedProtoApp/pull/26

**Comment by ykorobitsin** [comment]
Merge request: https://github.com/TelemedDevGroup/TelemedProtoApp/pull/27

**Comment by ro-jar** [comment]
i've tuned a bit structure and ordering of elements in readme.md
